common/models/Author.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%author}}".
 *
 * @property int $id
 * @property string $name
 * @property string|null $patronymic
 * @property string $surname
 */
class Author extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%author}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'surname'], 'required'],
            [['name', 'patronymic'], 'string', 'max' => 255],
            [['surname'], 'string', 'min' => 3],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJournalAuthors()
    {
        return $this->hasMany(JournalAuthor::class, ['author_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJournals()
    {
        return $this->hasMany(Journal::class, ['id' => 'journal_id'])->via('journalAuthors');
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('author', 'ID'),
            'name' => Yii::t('author', 'Name'),
            'patronymic' => Yii::t('author', 'Patronymic'),
            'surname' => Yii::t('author', 'Surname'),
        ];
    }

    /**
     * {@inheritdoc}
     * @return AuthorQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AuthorQuery(get_called_class());
    }
}

frontend/controllers/AuthorController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Author;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthorController implements the CRUD actions for Author model.
 */
class AuthorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Author models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Author::find(),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Author model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Author model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Author();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Author model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Author model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionList($id)
    {

    }

    /**
     * Finds the Author model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Author the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Author::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/controllers/JournalController.php
<?php

namespace frontend\controllers;

use common\helpers\UploadError;
use common\models\Author;
use common\models\JournalAuthor;
use Yii;
use common\models\Journal;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * JournalController implements the CRUD actions for Journal model.
 */
class JournalController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Journal models.
     *
     * @var $id integer Author id
     * @return mixed
     */
    public function actionIndex($id = 0)
    {
        if ($id) {
            $query = Journal::find()
                ->joinWith([
                    'authors' => function($query) use ($id) {
                        /**
                         * @var $query ActiveQuery
                         */
                        $query->where('{{author}}.id='.$id)->alias('author');
                    }
                ]);
        } else {
            $query = Journal::find()->joinWith('authors');
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        if ($id) {
            $viewData = [
                'dataProvider' => $dataProvider,
                'author' => Author::findOne($id),
            ];
        } else {
            $viewData = [
                'dataProvider' => $dataProvider,
                'author' => null
            ];
        }
        return $this->render('index', $viewData);
    }

    /**
     * Displays a single Journal model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id, ['authors']),
        ]);
    }

    /**
     * Creates a new Journal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Journal();

        $isPostRequest = Yii::$app->request->isPost;
        $transactionResult = false;
        $post = Yii::$app->request->post();
        if ($isPostRequest && $model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            $modelName = $model->formName();
            $postData = Yii::$app->request->post($modelName);

            $image = UploadedFile::getInstance($model, 'image_file');
            if (!empty($image)) {
                if ($image->error) {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', UploadError::getErrorMessage($image->error));
                    return $this->redirect('index');
                }
            } else {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', Yii::t('journal','Image was not loaded'));
                return $this->redirect('index');
            }

            $hash = substr(md5($image->baseName . '.' . $image->extension . time()), 0 , 16);
            $path = 'uploads/' . $hash . '.' . $image->extension;
            $image->saveAs($path);
            $model->image_path = $path;

            $journalSaved =  $model->save();
            if ($journalSaved) {
                $authorList = $postData['authorList'];

                $items = [];
                foreach ($authorList as $authorID) {
                    $items[] = [
                        $authorID, $model->id
                    ];
                }

                $linkCount = Yii::$app->db->createCommand()->batchInsert(
                    '{{%journal_author}}',
                    ['author_id', 'journal_id'],
                    $items
                )->execute();

                if ($linkCount) {
                    $transaction->commit();
                    $transactionResult = true;
                } else {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', Yii::t('journal', 'Something is wrong'));
                    return $this->redirect('index');
                }
            } else {
                Yii::$app->session->setFlash('error', Yii::t('journal', 'Can`t save journal.'));
                Yii::error(var_export($model->errors, true));
                $transaction->rollBack();
                return $this->redirect('index');
            }
        }

        if ($isPostRequest && $transactionResult) {
            Yii::$app->session->setFlash('success', UploadError::getErrorMessage());
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $authors = Author::find()->all();

        return $this->render('create', [
            'model' => $model,
            'authors' => $authors
        ]);
    }

    /**
     * Updates an existing Journal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id, ['authors']);

        $currentAuthorIds = ArrayHelper::getColumn($model->authors, 'id');

        $isPostRequest = Yii::$app->request->isPost;
        $transactionResult = false;

        if ($isPostRequest && $model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            $modelName = $model->formName();
            $postData = Yii::$app->request->post($modelName);

            $image = UploadedFile::getInstance($model, 'image_file');
            if (!empty($image)) {
                if ($image->error) {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', UploadError::getErrorMessage($image->error));
                    return $this->redirect('index');
                }

                $hash = substr(md5($image->baseName . '.' . $image->extension . time()), 0 , 16);
                $path = 'uploads/' . $hash . '.' . $image->extension;
                $image->saveAs($path);
                $model->image_path = $path;
            }

            $journalSaved =  $model->save();
            if ($journalSaved) {
                //first, we need clear all links to authors associated with journal
                JournalAuthor::deleteAll(['and', ['in', 'author_id', $currentAuthorIds], ['journal_id' => $model->id]]);

                $authorList = $postData['authorList'];

                $items = [];
                foreach ($authorList as $authorID) {
                    $items[] = [
                        $authorID, $model->id
                    ];
                }

                if (!empty($items)) {
                    $linkCount = Yii::$app->db->createCommand()->batchInsert(
                        '{{%journal_author}}',
                        ['author_id', 'journal_id'],
                        $items
                    )->execute();

                    if ($linkCount) {
                        $transaction->commit();
                        $transactionResult = true;
                    } else {
                        $transaction->rollBack();
                        Yii::$app->session->setFlash('error', Yii::t('journal', 'Something is wrong'));
                        return $this->redirect('index');
                    }
                } else {
                    $transaction->commit();
                    $transactionResult = true;
                }
            } else {
                Yii::$app->session->setFlash('error', Yii::t('journal', 'Can`t save journal.'));
                Yii::error(var_export($model->errors, true));
                $transaction->rollBack();
                return $this->redirect('index');
            }
        }

        if ($isPostRequest && $transactionResult) {
            Yii::$app->session->setFlash('success', UploadError::getErrorMessage());
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $authors = Author::find()->all();

        $dropDownListOptions = [];
        foreach ($currentAuthorIds as $cID) {
            $dropDownListOptions[$cID] = ['selected' => true];
        }
        $dropDownListOptions = [
            'options' => $dropDownListOptions
        ];

        return $this->render('update', [
            'model' => $model,
            'authors' => $authors,
            'dropDownListOptions' => $dropDownListOptions,
            'isUpdate' => true,
        ]);
    }

    /**
     * Deletes an existing Journal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Journal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Journal the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, array $with = [])
    {
        if (empty($with)) {
            if (($model = Journal::findOne($id)) !== null) {
                return $model;
            }
        } else {

frontend/views/author/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Author */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="author-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'patronymic')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/author/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Author */

$this->title = Yii::t('author', 'Create Author');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Authors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="author-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/author/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('author', 'Authors');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="author-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('author', 'Create Author'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'patronymic',
            'surname',
            [
                'class' => \yii\grid\DataColumn::class,
                'label' => Yii::t('author', 'authors magazines'),
                'content' => function ($model, $key, $index, $column) {
                    $span = '<span class="glyphicon glyphicon-book"></span>';
                    $content = Html::a($span, ['journal/index', 'id' => $model->id]);
                    return '<div class="journal_centered">' . $content . '</div>';
                },
                'headerOptions' => [
                    'class' => 'journal_header_centered',
                ],
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

frontend/views/author/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Author */

$this->title = Yii::t('author', 'Update Author: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('author', 'Authors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="author-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/author/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\web\YiiAsset;

/* @var $this yii\web\View */
/* @var $model common\models\Author */

$this->title = $model->surname . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('author', 'Authors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);
?>
<div class="author-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('author', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('author', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a(Yii::t('author', 'Show journal list'), ['journal/index', 'id' => $model->id], ['class' => 'btn btn-success']); ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'patronymic',
            'surname',
        ],
    ]) ?>

</div>