common/models/Journal.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;
use \yii\db\ActiveRecord;
use \yii\db\ActiveQuery;

/**
 * This is the model class for table "{{%journal}}".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $description
 * @property resource|null $image_file
 * @property string|null $issue_date
 */
class Journal extends ActiveRecord
{
    /**
     * @var array List of authors. Virtual field
     */
    private $authorList;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%journal}}';
    }

    const SCENARIO_INSERT = 'insert';

    const SCENARIO_UPDATE = 'update';

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['issue_date', 'name'], 'required'],
            [['image_file'], 'required', 'on' => static::SCENARIO_INSERT],
            [['image_file'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, jpeg', 'maxSize' => 2*1024*1024, 'on' => static::SCENARIO_INSERT],
            [['image_file'], 'file', 'extensions' => 'png, jpg, jpeg', 'maxSize' => 2*1024*1024, 'on' => static::SCENARIO_UPDATE],
            [['image_path'], 'string'],
            [['issue_date', 'authorList'], 'safe'],
            [['name', 'description'], 'string', 'max' => 255],
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getJournalAuthors()
    {
        return $this->hasMany(JournalAuthor::class, ['journal_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getAuthors()
    {
        return $this->hasMany(Author::class, ['id' => 'author_id'])->via('journalAuthors');
    }

    /**
     * @param $authorList
     */
    public function setAuthorList($authorList)
    {
        $this->authorList = $authorList;
    }

    /**
     * @return array
     */
    public function getAuthorList()
    {
        return $this->authorList;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('journal', 'ID'),
            'name' => Yii::t('journal', 'Name'),
            'description' => Yii::t('journal', 'Description'),
            'image_file' => Yii::t('journal', 'Image'),
            'image_path' => Yii::t('journal', 'Image'),
            'issue_date' => Yii::t('journal', 'Issue Date'),
            'authorList' => Yii::t('journal', 'Author List'),
        ];
    }

    public function attributes()
    {
        return ArrayHelper::merge(parent::attributes(), ['image_file']); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return JournalQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new JournalQuery(get_called_class());
    }
}

frontend/controllers/JournalController.php
<?php

namespace frontend\controllers;

use common\helpers\UploadError;
use common\models\Author;
use common\models\JournalAuthor;
use Yii;
use common\models\Journal;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * JournalController implements the CRUD actions for Journal model.
 */
class JournalController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Journal models.
     *
     * @var $id integer Author id
     * @return mixed
     */
    public function actionIndex($id = 0)
    {
        if ($id) {
            $query = Journal::find()
                ->joinWith([
                    'authors' => function($query) use ($id) {
                        /**
                         * @var $query ActiveQuery
                         */
                        $query->where('{{author}}.id='.$id)->alias('author');
                    }
                ]);
        } else {
            $query = Journal::find()->joinWith('authors');
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        if ($id) {
            $viewData = [
                'dataProvider' => $dataProvider,
                'author' => Author::findOne($id),
            ];
        } else {
            $viewData = [
                'dataProvider' => $dataProvider,
                'author' => null
            ];
        }
        return $this->render('index', $viewData);
    }

    /**
     * Displays a single Journal model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id, ['authors']),
        ]);
    }

    /**
     * Creates a new Journal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Journal();

        $isPostRequest = Yii::$app->request->isPost;
        $transactionResult = false;
        $post = Yii::$app->request->post();
        if ($isPostRequest && $model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            $modelName = $model->formName();
            $postData = Yii::$app->request->post($modelName);

            $image = UploadedFile::getInstance($model, 'image_file');
            if (!empty($image)) {
                if ($image->error) {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', UploadError::getErrorMessage($image->error));
                    return $this->redirect('index');
                }
            } else {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', Yii::t('journal','Image was not loaded'));
                return $this->redirect('index');
            }

            $hash = substr(md5($image->baseName . '.' . $image->extension . time()), 0 , 16);
            $path = 'uploads/' . $hash . '.' . $image->extension;
            $image->saveAs($path);
            $model->image_path = $path;

            $journalSaved =  $model->save();
            if ($journalSaved) {
                $authorList = $postData['authorList'];

                $items = [];
                foreach ($authorList as $authorID) {
                    $items[] = [
                        $authorID, $model->id
                    ];
                }

                $linkCount = Yii::$app->db->createCommand()->batchInsert(
                    '{{%journal_author}}',
                    ['author_id', 'journal_id'],
                    $items
                )->execute();

                if ($linkCount) {
                    $transaction->commit();
                    $transactionResult = true;
                } else {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', Yii::t('journal', 'Something is wrong'));
                    return $this->redirect('index');
                }
            } else {
                Yii::$app->session->setFlash('error', Yii::t('journal', 'Can`t save journal.'));
                Yii::error(var_export($model->errors, true));
                $transaction->rollBack();
                return $this->redirect('index');
            }
        }

        if ($isPostRequest && $transactionResult) {
            Yii::$app->session->setFlash('success', UploadError::getErrorMessage());
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $authors = Author::find()->all();

        return $this->render('create', [
            'model' => $model,
            'authors' => $authors
        ]);
    }

    /**
     * Updates an existing Journal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id, ['authors']);

        $currentAuthorIds = ArrayHelper::getColumn($model->authors, 'id');

        $isPostRequest = Yii::$app->request->isPost;
        $transactionResult = false;

        if ($isPostRequest && $model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            $modelName = $model->formName();
            $postData = Yii::$app->request->post($modelName);

            $image = UploadedFile::getInstance($model, 'image_file');
            if (!empty($image)) {
                if ($image->error) {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', UploadError::getErrorMessage($image->error));
                    return $this->redirect('index');
                }

                $hash = substr(md5($image->baseName . '.' . $image->extension . time()), 0 , 16);
                $path = 'uploads/' . $hash . '.' . $image->extension;
                $image->saveAs($path);
                $model->image_path = $path;
            }

            $journalSaved =  $model->save();
            if ($journalSaved) {
                //first, we need clear all links to authors associated with journal
                JournalAuthor::deleteAll(['and', ['in', 'author_id', $currentAuthorIds], ['journal_id' => $model->id]]);

                $authorList = $postData['authorList'];

                $items = [];
                foreach ($authorList as $authorID) {
                    $items[] = [
                        $authorID, $model->id
                    ];
                }

                if (!empty($items)) {
                    $linkCount = Yii::$app->db->createCommand()->batchInsert(
                        '{{%journal_author}}',
                        ['author_id', 'journal_id'],
                        $items
                    )->execute();

                    if ($linkCount) {
                        $transaction->commit();
                        $transactionResult = true;
                    } else {
                        $transaction->rollBack();
                        Yii::$app->session->setFlash('error', Yii::t('journal', 'Something is wrong'));
                        return $this->redirect('index');
                    }
                } else {
                    $transaction->commit();
                    $transactionResult = true;
                }
            } else {
                Yii::$app->session->setFlash('error', Yii::t('journal', 'Can`t save journal.'));
                Yii::error(var_export($model->errors, true));
                $transaction->rollBack();
                return $this->redirect('index');
            }
        }

        if ($isPostRequest && $transactionResult) {
            Yii::$app->session->setFlash('success', UploadError::getErrorMessage());
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $authors = Author::find()->all();

        $dropDownListOptions = [];
        foreach ($currentAuthorIds as $cID) {
            $dropDownListOptions[$cID] = ['selected' => true];
        }
        $dropDownListOptions = [
            'options' => $dropDownListOptions
        ];

        return $this->render('update', [
            'model' => $model,
            'authors' => $authors,
            'dropDownListOptions' => $dropDownListOptions,
            'isUpdate' => true,
        ]);
    }

    /**
     * Deletes an existing Journal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Journal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Journal the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, array $with = [])
    {
        if (empty($with)) {
            if (($model = Journal::findOne($id)) !== null) {
                return $model;
            }
        } else {

frontend/views/journal/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model common\models\Journal */
/* @var $form yii\widgets\ActiveForm */
/* @var $authors common\models\Author[] */
/* @var $dropDownListOptions array|null */
/* @var $isUpdate bool|null */

$authorList = [];
foreach ($authors as $author) {
    $authorList[$author->id] = $author->surname . ' ' . $author->name . ' ' . $author->patronymic;
}
$options = [
    'prompt' => 'Выберите автора...',
    'multiple' => true,
];
if (!empty($dropDownListOptions)) {
    $options = ArrayHelper::merge($options, $dropDownListOptions);
}
$isUpdate = $isUpdate ?? false;
?>

<div class="journal-form">

    <?php $form = ActiveForm::begin(); ?>

        <div class="container">

            <div class="row">

                <div class="col-md-4">

                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

                </div>

            </div>

            <div class="row">

                <div class="col-md-5">

                    <?= $form->field($model, 'description')->textarea(['maxlength' => true, 'rows' => 5, 'cols' => 7]) ?>

                </div>

            </div>

            <?php if (!$isUpdate) { ?>
                <div class="row">

                    <div class="col-md-3">

                        <?= $form->field($model, 'image_file')->fileInput() ?>

                    </div>

                </div>
            <?php } else { ?>
                <div class="row">

                    <div class="col-md-3">

                        <?php
                            $imageUrl = Yii::$app->request->hostInfo . DIRECTORY_SEPARATOR . $model->image_path;
                            $image = '<img src="' . $imageUrl . '" width="100" height="100" alt="">';
                            echo Html::a($image, $imageUrl, [
                                'class' => 'magazine_cover',
                                'data-lightbox' => 'image',
                            ]);
                        ?>

                    </div>

                </div>
            <?php } ?>

            <div class="row">

                <div class="col-md-3 mt10">
                    <div><?= Yii::t('journal', 'Issue Date') ?></div>
                    <?php
                        echo DatePicker::widget([
                        'model' => $model,
                        'attribute' => 'issue_date',
                        'language' => 'ru',
                        'dateFormat' => 'yyyy-MM-dd',
                        ]);
                    ?>
                </div>

            </div>

            <div class="row">

                <div class="col-md-3">

                    <?= $form->field($model, 'authorList')->dropDownList($authorList, $options) ?>

                </div>

            </div>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('journal', 'Save'), ['class' => 'btn btn-success']) ?>
            </div>

        </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/journal/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Journal */
/* @var $authors common\models\Author[] */

$this->title = Yii::t('journal', 'Create Journal');
$this->params['breadcrumbs'][] = ['label' => Yii::t('journal', 'Journals'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="journal-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'authors' => $authors
    ]) ?>

</div>

frontend/views/journal/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use frontend\assets\JournalAsset;
use yii\helpers\Url;
use common\models\Journal;
use common\models\Author;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $author \common\models\Author|null */

$this->title = Yii::t('journal', 'Journals');
$this->params['breadcrumbs'][] = $this->title;
JournalAsset::register($this);
?>
<div class="journal-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
        if (!empty($author)) {
            ?>
                <h3>
                    <span class="author_journal_title">
                    <?= Yii::t('journal', 'List of author\'s journals: {name} {surname}',
                        ['name' => $author->name, 'surname' => $author->surname]) ?>
                    </span>
                </h3>
            <?php
        }
    ?>

    <p>
        <?= Html::a(Yii::t('journal', 'Create Journal'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            [
                'content' => function ($model, $key, $index, $column) {
                    /**
                     * @var $model Journal
                     */
                    return Html::a($model->name, ['journal/view', 'id' => $model->id]);
                },
                'header' => Html::a(
                    Yii::t('journal', 'Name'),
                    Url::to(['journal/index', 'sort' => 'name']),
                    [
                        'data-sort' => '-name',
                        'class' => 'asc'
                    ]
                )
            ],
            [
                'header' => Html::a(Yii::t('journal', 'Description'), '#'),
                'label' => Yii::t('journal', 'description'),
                'format' => 'raw',
                'value' => function ($model, $key, $index, $column) {
                    /**
                     * @var $model Journal
                     */
                    return $model->description;
                },
                'contentOptions'=>['style'=>'max-width: 250px;']
            ],
            [
                'label' =>  Yii::t('journal', 'authors'),
                'header' => Html::a(Yii::t('journal', 'authors'), '#'),
                'content' => function ($model, $key, $index, $column) {
                    $authorListStr = '';
                    foreach ($model->authors as $author) {
                        /**
                         * @var $author Author
                         */
                        $authorListStr .= $author->surname  . ' ' . $author->name . ' ' . $author->patronymic . '<br  />';
                    }
                    return $authorListStr;
                }
            ],
            [
                'header' => Yii::t('journal', 'Magazine cover'),
                'content' => function ($model, $key, $index, $column) {
                    $imageUrl = Yii::$app->request->hostInfo . DIRECTORY_SEPARATOR . $model->image_path;
                    $image = '<img src="' . $imageUrl . '" width="100" height="100" alt="">';
                    return Html::a($image, $imageUrl, [
                        'class' => 'magazine_cover',
                        'data-lightbox' => 'image',
                    ]);
                }
            ],
            'issue_date',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

frontend/views/journal/update.php
<?php

use yii\helpers\Html;
use frontend\assets\JournalAsset;

/* @var $this yii\web\View */
/* @var $model common\models\Journal */
/* @var $authors common\models\Author[] */
/* @var $dropDownListOptions array|null */
/* @var $isUpdate bool */

JournalAsset::register($this);

$dropDownListOptions = $dropDownListOptions ?? [];

$this->title = Yii::t('journal', 'Update Journal: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('journal', 'Journals'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('journal', 'Update');
?>
<div class="journal-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'authors' => $authors,
        'dropDownListOptions' => $dropDownListOptions,
        'isUpdate' => $isUpdate,
    ]) ?>

</div>

frontend/views/journal/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use frontend\assets\JournalAsset;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model common\models\Journal */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('journal', 'Journals'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
JournalAsset::register($this);
?>
<div class="journal-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('journal', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('journal', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('journal', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?php
        $authors = $model->authors;
        $attributes = [
            'id',
            'name',
            'description',
            'issue_date',
        ];
        $authorsAttribute = [[
            'label' => Yii::t('journal', 'Authors'),
            'value' => function($model, $widget) use ($authors) {
                $authors = array_map(
                    function($n, $p, $s) {
                        return '<div>' . $n . ' ' . $p . ' ' . $s . '</div>';
                    },
                    ArrayHelper::getColumn($authors, 'name'),
                    ArrayHelper::getColumn($authors, 'patronymic'),
                    ArrayHelper::getColumn($authors, 'surname')
                );

                return implode(' ', $authors);
            },
            'format' => 'raw',
        ]];
        $attributes = ArrayHelper::merge($attributes, $authorsAttribute);
        if ($model->image_path) {
            $imageAttribute = [[
                'attribute' => 'image_path',
                'value' => function($model, $widget) {
                    $imageUrl = Yii::$app->request->hostInfo . DIRECTORY_SEPARATOR . $model->image_path;
                    $image = '<img src="' . $imageUrl . '" width="100" height="100" alt="" class="magazine_cover">';
                    return Html::a($image, $imageUrl, [
                        'class' => 'magazine_cover',
                        'data-lightbox' => 'image',
                    ]);
                },
                'format' => 'raw',
            ]];
            $attributes = ArrayHelper::merge($attributes, $imageAttribute);
        }
        /*var_export($attributes);
        Yii::$app->end();*/
    ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => $attributes,
    ]) ?>

</div>